import React, { useEffect, useCallback, useState } from 'react';
import { DataView, Button, textStyle } from '@aragon/ui';

const FarmTable: React.FC = () => {
    
    
    return(
        <div>
            <DataView 
                fields={['Asset', 'Base Yield', 'Reward Yield', 'Total Yield', 'Reward Asset', '']}
                entries={[
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> },
                    {asset:"Honey", baseYield: "40%", rewardYield: "70%", totalYield: "110%", rewardAsset: "HNY", button:<Button>Deposit</Button> }
                ]}
                renderEntry = {({asset, baseYield, rewardYield, totalYield, rewardAsset, button}) => {
                    return [asset, baseYield, rewardYield, totalYield, rewardAsset, button]}
                   
                }
            />
        </div>
    )
}

export default FarmTable;